### ISSUE TITLE
Change your Render method in index.js

### ISSUE THREAD

**Issue by imshines** [daudi13/space-travel#32]
Hi, I noticed that you are using React 18 but you aren't using the new createRoot api you need to change that in order to use React 18 features.

Here's the code
```
// Before
import { render } from 'react-dom';
const container = document.getElementById('app');
render(<App tab="home" />, container);

// After
import { createRoot } from 'react-dom/client';
const container = document.getElementById('app');
const root = createRoot(container);
root.render(<App tab="home" />);
```

Reference [How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)

**Comment by daudi13** [comment]
thanks for bringing this up.
